 version: "3.8"
 services:
    web:
       build: ./frontend
       ports:
       - 3000:3000

    api:
      build: ./backend
      ports:
         - 4000:4000
      environment:
       DB_URL: mongodb://db/jackie's

    db:
        image: mongo:4.0-xenial
        ports:
          - 27017:27017
        volumes:
          - Jackie:/data/db        
 volumes:
  Jackie:
 
   